with 

source as (

    select * from {{ source('Raw_data', 'Events_Leverkusen') }}

),

renamed as (

    select
        int64_field_0,
        50_50,
        bad_behaviour_card,
        ball_recovery_recovery_failure,
        block_deflection,
        block_save_block,
        clearance_aerial_won,
        clearance_body_part,
        clearance_head,
        clearance_left_foot,
        clearance_right_foot,
        counterpress,
        dribble_nutmeg,
        dribble_outcome,
        duel_outcome,
        duel_type,
        duration,
        foul_committed_advantage,
        foul_committed_card,
        foul_committed_penalty,
        foul_won_advantage,
        foul_won_defensive,
        foul_won_penalty,
        id,
        `index`,
        interception_outcome,
        `location`,
        match_id,
        off_camera,
        `out`,
        pass_aerial_won,
        pass_angle,
        pass_assisted_shot_id,
        pass_body_part,
        pass_cross,
        pass_cut_back,
        pass_deflected,
        pass_end_location,
        pass_goal_assist,
        pass_height,
        pass_inswinging,
        pass_length,
        pass_outcome,
        pass_outswinging,
        pass_recipient,
        pass_recipient_id,
        pass_shot_assist,
        pass_switch,
        pass_technique,
        pass_through_ball,
        pass_type,
        `period` as event_period,
        play_pattern,
        player,
        player_id,
        position,
        possession,
        possession_team,
        possession_team_id,
        related_events,
        shot_aerial_won,
        shot_body_part,
        shot_end_location,
        shot_first_time,
        shot_freeze_frame,
        shot_key_pass_id,
        shot_one_on_one,
        shot_outcome,
        shot_statsbomb_xg,
        shot_technique,
        shot_type,
        substitution_outcome,
        substitution_outcome_id,
        substitution_replacement,
        substitution_replacement_id,
        tactics,
        team,
        team_id,
        timestamp,
        `type` as event_type,
        under_pressure,
        ball_recovery_offensive,
        block_offensive,
        dribble_overrun,
        foul_committed_type,
        miscontrol_aerial_won,
        foul_committed_offensive,
        shot_deflected,
        pass_miscommunication,
        pass_no_touch,
        pass_straight,
        shot_open_goal,
        dribble_no_touch,
        shot_saved_off_target,
        shot_saved_to_post,
        clearance_other,
        goalkeeper_success_in_play

    from source

)

select * from renamed